import createCallToActionElementDescriptor from './widgets/createCallToActionElementDescriptor';
import createSideBySideElementDescriptor from './widgets/createSideBySideElementDescriptor';
import createFeatureListElementDescriptor from './widgets/createFeatureListElementDescriptor';
import registerCustomElement from '@dojo/widget-core/registerCustomElement';

registerCustomElement(createCallToActionElementDescriptor);
registerCustomElement(createSideBySideElementDescriptor);
registerCustomElement(createFeatureListElementDescriptor);
